name: pdfmakr_example
description: a pdfmakr example
version: 0.0.2

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  dart2_constant: ^1.0.1
  pdfmakr:
    path: ../

dev_dependencies:
  build_runner: '>=0.8.10 <0.11.0'
  build_web_compilers: '>=0.3.6 <0.5.0'

web:
  compiler:
    debug: dartdevc
