name: pdfmakr
description: A dart wrapper for http://pdfmake.org/ (browser only)
version: 0.0.1+2
homepage: https://github.com/rxlabz/pdfmakr
author: rxlabz <dev@rxla.bz>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  js: '^0.6.1'

